apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80