apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
spec:
  selector:
    project: roboshop
    component: frontend
    tier: frontend
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80